name: FPL ETL CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Install Python & dependencies
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Run pytest
    - name: Test with pytest
      run: |
        export PYTHONPATH=$(pwd)
        pytest

    # Run security checks
    - name: Run bandit checks
      run: |
        bandit -lll */*.py *c/*/*.py

    # # Check coverage
    # - name: Get Cover 
    #   uses: orgoro/coverage@v3.2
    #   with:
    #       coverageFile: coverage.xml
    #       token: $'{{ secrets.GITHUB_TOKEN }}
